"""empty message

Revision ID: 6d4df9e2c0d3
Revises: e5b13c9f0e7c
Create Date: 2022-08-16 11:24:40.689171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d4df9e2c0d3'
down_revision = 'e5b13c9f0e7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website_link', sa.String(length=500), nullable=True))
    op.add_column('Artist', sa.Column('seeking_performances', sa.Boolean(), nullable=True))
    op.add_column('Artist', sa.Column('seeking_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'seeking_description')
    op.drop_column('Artist', 'seeking_performances')
    op.drop_column('Artist', 'website_link')
    # ### end Alembic commands ###
